/*LINGUAGEM DDL */

/*criando banco de dados*/
CREATE DATABASE IF NOT EXISTS PHP7 /*Caso nao exista o banco o camando cria*/

/*SELECIONANDO BANCO DE DADOS*/

USE PHP7;

/*CRIANDO TABELAS*/

CREATE TABLE IF NOT EXISTS ESTUDANTES
(
    ID BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    IDADE INT(3) NULL,
    ALTURA FLOAT(10.2) NULL
    );

/*MOSTRANDO TODOS OS BANCOS DE DADOS*/
SHOW DATABASES

/* PODEMOS BUSCAR UM BANCO DE DADOS */
SHOW DATABASES LIKE 'PHP7' /*PELO NOME*/
SHOW DATABASES LIKE '%PHP7' /*QUE COMECE COM*/
SHOW DATABASES LIKE '%7%' /*QUE CONTENHA*/


